# Q1

In [3]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Q2

In [7]:
a=[]
for i in range(5):
    a.append(int(input()))


b=[]
for j in range(5):
    b.append(int(input()))
    
print("list 1",a)
print("list 2",b)

print()
    
arr=np.array(a)
print("Array 1:",arr)
print()

arr2=np.array(b)
print("Array 2:",arr2)
print()

arr3=np.concatenate((arr , arr2))

print("Concatenated array:",arr3)
print()

arr4 = np.sort(arr3)
print("Sorted Array:",arr4)
 

22
33
65
12
32
76
89
23
54
13
list 1 [22, 33, 65, 12, 32]
list 2 [76, 89, 23, 54, 13]

Array 1: [22 33 65 12 32]

Array 2: [76 89 23 54 13]

Concatenated array: [22 33 65 12 32 76 89 23 54 13]

Sorted Array: [12 13 22 23 32 33 54 65 76 89]


# Q3:-

In [8]:
arr1=np.arange(10)
print(arr1)
print("dimension:",arr1.ndim)
print("size:",arr1.size)
print()

arr2=np.arange(10).reshape(2,5)
print(arr2)
print("dimension:",arr2.ndim)
print("size:",arr2.size)


[0 1 2 3 4 5 6 7 8 9]
dimension: 1
size: 10

[[0 1 2 3 4]
 [5 6 7 8 9]]
dimension: 2
size: 10


# Q4:- 

In [10]:
arr=np.array([1,2,3,4,5,6,6])
print(arr.shape)
print(arr.ndim)
print()

arr2=arr[np.newaxis, :]
print(arr2.shape)
print(arr2.ndim)
print()

arr3 = np.expand_dims(arr, axis=0)
print(arr3.shape)
print(arr3.ndim)

(7,)
1

(1, 7)
2

(1, 7)
2


# Q5

In [11]:
arr1=np.array([[1,1],[2,2]])
print(arr1)
print()
arr2= np.array([[3,3],[4,4]])
print(arr2)
print()

print(np.vstack((arr1,arr2)))
print()
print(np.hstack((arr1,arr2)))

[[1 1]
 [2 2]]

[[3 3]
 [4 4]]

[[1 1]
 [2 2]
 [3 3]
 [4 4]]

[[1 1 3 3]
 [2 2 4 4]]


# Q6:-



In [15]:
a = [1, 1, 2, 2, 3,4,4,3]
print("List:",a)
b = set(a)
print("Unique Items:",b)
c = len(b)
print("No. of Unique items:",c)

List: [1, 1, 2, 2, 3, 4, 4, 3]
Unique Items: {1, 2, 3, 4}
No. of Unique items: 4
